[versions]
agp = "8.1.2"
kotlin = "1.9.10"

min_sdk_version = "21"
target_sdk_version = "34"
compile_sdk_version = "34"

[libraries]
corektx = "androidx.core:core-ktx:1.13.1"
appcompat = "androidx.appcompat:appcompat:1.6.1"
material = "com.google.android.material:material:1.12.0"

[bundles]
